In [161]:
import pandas as pd
import numpy as np
from sklearn.metrics.pairwise import pairwise_distances 
from scipy import sparse
from sklearn.metrics.pairwise import cosine_similarity
from scipy.spatial.distance import cosine


# 1. Collaborative Filtering

In [590]:
df = pd.read_csv('radio_songs.csv')

In [558]:
df.head()

user  a perfect circle  abba  ac/dc  adam green  aerosmith  afi  air  \
0     1                 0     0      0           0          0    0    0   
1    33                 0     0      0           1          0    0    0   
2    42                 0     0      0           0          0    0    0   
3    51                 0     0      0           0          0    0    0   
4    62                 0     0      0           0          0    0    0   

   alanis morissette  alexisonfire  ...  timbaland  tom waits  tool  \
0                  0             0  ...          0          0     0   
1                  0             0  ...          0          0     0   
2                  0             0  ...          0          0     0   
3                  0             0  ...          0          0     0   
4                  0             0  ...          0          0     0   

   tori amos  travis  trivium  u2  underoath  volbeat  yann tiersen  
0          0       0        0   0          0        0             0  
1          0       0        0   0          0        0             0  
2          0       0        0   0          0        0             0  
3          0       0        0   0          0        0             0  
4          0       0        0   0          0        0             0  

[5 rows x 286 columns]

In [559]:
df.shape

(100, 286)

In [110]:
df.dropna

<bound method DataFrame.dropna of     user  a perfect circle  abba  ac/dc  adam green  aerosmith  afi  air  \
0      1                 0     0      0           0          0    0    0   
1     33                 0     0      0           1          0    0    0   
2     42                 0     0      0           0          0    0    0   
3     51                 0     0      0           0          0    0    0   
4     62                 0     0      0           0          0    0    0   
..   ...               ...   ...    ...         ...        ...  ...  ...   
95  1566                 0     0      0           0          0    0    0   
96  1586                 0     0      0           0          0    0    0   
97  1589                 0     0      0           0          0    0    0   
98  1601                 0     0      0           0          0    0    0   
99  1606                 0     1      0           0          0    0    0   

    alanis morissette  alexisonfire  ...  timbaland  

In [106]:
df.isna

<bound method DataFrame.isnull of     user  a perfect circle  abba  ac/dc  adam green  aerosmith  afi  air  \
0      1                 0     0      0           0          0    0    0   
1     33                 0     0      0           1          0    0    0   
2     42                 0     0      0           0          0    0    0   
3     51                 0     0      0           0          0    0    0   
4     62                 0     0      0           0          0    0    0   
..   ...               ...   ...    ...         ...        ...  ...  ...   
95  1566                 0     0      0           0          0    0    0   
96  1586                 0     0      0           0          0    0    0   
97  1589                 0     0      0           0          0    0    0   
98  1601                 0     0      0           0          0    0    0   
99  1606                 0     1      0           0          0    0    0   

    alanis morissette  alexisonfire  ...  timbaland  

## Item-Item collaborative filtering

We have to construct a new item by item matrix and determine the relationships between the artists. Using the cosine similarity , we can calculate the correlation between the artits. cosine similarity of 1 means perfect similarity where as cosine similarity of 0 means no correlation .

In [562]:
# Dropping the user column to construct a item-item matrix
artists_matrix = df.drop('user', 1)

In [563]:
artists_matrix.head()

a perfect circle  abba  ac/dc  adam green  aerosmith  afi  air  \
0                 0     0      0           0          0    0    0   
1                 0     0      0           1          0    0    0   
2                 0     0      0           0          0    0    0   
3                 0     0      0           0          0    0    0   
4                 0     0      0           0          0    0    0   

   alanis morissette  alexisonfire  alicia keys  ...  timbaland  tom waits  \
0                  0             0            0  ...          0          0   
1                  0             0            0  ...          0          0   
2                  0             0            0  ...          0          0   
3                  0             0            0  ...          0          0   
4                  0             0            0  ...          0          0   

   tool  tori amos  travis  trivium  u2  underoath  volbeat  yann tiersen  
0     0          0       0        0   0          0        0             0  
1     0          0       0        0   0          0        0             0  
2     0          0       0        0   0          0        0             0  
3     0          0       0        0   0          0        0             0  
4     0          0       0        0   0          0        0             0  

[5 rows x 285 columns]

In [564]:
# Creating a placeholder matrix for item-item similarity
temp_df = pd.DataFrame(index=artists_matrix.columns,columns=artists_matrix.columns)

In [565]:
for i in range(0,len(temp_df.columns)) :
    # Looping through each of the artists columns
    for j in range(0,len(temp_df.columns)) :
# Filling in the NaNs in the temp_df or the placeholder matrix with the item-item similarities using the spatial distance with cosine
      temp_df.iloc[i,j] = 1 - cosine(artists_matrix.iloc[:,i],artists_matrix.iloc[:,j])

/opt/anaconda3/lib/python3.7/site-packages/scipy/spatial/distance.py:720: RuntimeWarning: invalid value encountered in double_scalars
  dist = 1.0 - uv / np.sqrt(uu * vv)


In [566]:
temp_df

a perfect circle abba     ac/dc adam green aerosmith  \
a perfect circle              NaN  NaN       NaN        NaN       NaN   
abba                          NaN    1         0          0         0   
ac/dc                         NaN    0         1          0         0   
adam green                    NaN    0         0          1         0   
aerosmith                     NaN    0         0          0         1   
...                           ...  ...       ...        ...       ...   
trivium                       NaN    0         0          0         0   
u2                            NaN    0  0.223607          0         0   
underoath                     NaN    0         0          0         0   
volbeat                       NaN    0       0.2          0         0   
yann tiersen                  NaN    0         0          0         0   

                       afi  air alanis morissette alexisonfire alicia keys  \
a perfect circle       NaN  NaN               NaN          NaN         NaN   
abba                     0    0                 0            0           0   
ac/dc             0.223607    0                 0            0           0   
adam green               0    0                 0            0           0   
aerosmith                0    0                 0            0           0   
...                    ...  ...               ...          ...         ...   
trivium                  0    0                 0            0           0   
u2                       0    0                 0            0           0   
underoath                0    0                 0     0.288675           0   
volbeat                  0    0                 0            0           0   
yann tiersen             0    0                 0            0           0   

                  ... timbaland tom waits      tool tori amos travis  \
a perfect circle  ...       NaN       NaN       NaN       NaN    NaN   
abba              ...         0         0         0         0    NaN   
ac/dc             ...         0         0         0         0    NaN   
adam green        ...         0         0         0         0    NaN   
aerosmith         ...         0         0         0         0    NaN   
...               ...       ...       ...       ...       ...    ...   
trivium           ...         0         0         0         0    NaN   
u2                ...         0         0         0         0    NaN   
underoath         ...         0  0.204124         0         0    NaN   
volbeat           ...         0         0  0.447214         0    NaN   
yann tiersen      ...         0         0         1         0    NaN   

                   trivium        u2 underoath   volbeat yann tiersen  
a perfect circle       NaN       NaN       NaN       NaN          NaN  
abba                     0         0         0         0            0  
ac/dc                    0  0.223607         0       0.2            0  
adam green               0         0         0         0            0  
aerosmith                0         0         0         0            0  
...                    ...       ...       ...       ...          ...  
trivium                  1         0         0  0.223607            0  
u2                       0         1         0  0.223607            0  
underoath                0         0         1         0            0  
volbeat           0.223607  0.223607         0         1     0.447214  
yann tiersen             0         0         0  0.447214            1  

[285 rows x 285 columns]

In [577]:
# Building a close neighbourhood for closest similar items/artists
item_similarity_matrix = pd.DataFrame(index=temp_df.columns,columns=range(1,12))

In [578]:
item_similarity_matrix

1    2    3    4    5    6    7    8    9   10   11
a perfect circle  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
abba              NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
ac/dc             NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
adam green        NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
aerosmith         NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
...               ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...
trivium           NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
u2                NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
underoath         NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
volbeat           NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
yann tiersen      NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN

[285 rows x 11 columns]

In [579]:
# Looping through the entire item-similarity matrix and filling in the values with the closest neighbourhood items/artists
for i in range(0,len(temp_df.columns)):
    item_similarity_matrix.iloc[i,:11] = temp_df.iloc[0:,i].sort_values(ascending=False)[:11].index

In [580]:
item_similarity_df = item_similarity_matrix.transpose()
item_similarity_df

a perfect circle             abba            ac/dc           adam green  \
1    a perfect circle             abba            ac/dc           adam green   
2                abba      hans zimmer       hammerfall       nouvelle vague   
3               ac/dc    frank sinatra       in extremo     three days grace   
4          adam green     howard shore        metallica             the fray   
5           aerosmith    elvis presley    dream theater                keane   
6                 afi  groove coverage   blind guardian       tegan and sara   
7                 air        faithless  bloodhound gang  belle and sebastian   
8   alanis morissette       papa roach        nightwish          the strokes   
9        alexisonfire      limp bizkit   marilyn manson           razorlight   
10        alicia keys          scooter    frank sinatra         farin urlaub   
11   all that remains        nightwish     apocalyptica            the kooks   

         aerosmith                afi                air  alanis morissette  \
1        aerosmith                afi                air  alanis morissette   
2           staind           paramore               moby          the clash   
3       maria mena             sum 41          faithless             r.e.m.   
4   flogging molly  breaking benjamin          radiohead              bjork   
5     bad religion               nofx  alanis morissette          tori amos   
6        morcheeba          anti-flag              bjork       jimi hendrix   
7     eric clapton          blink-182          nada surf            nirvana   
8       papa roach     good charlotte          tori amos        damien rice   
9       audioslave          peter fox        the streets       bad religion   
10       manu chao             clueso                atb          motorhead   
11      in extremo            ramones          daft punk           the cure   

            alexisonfire         alicia keys  ...              timbaland  \
1           alexisonfire         alicia keys  ...              timbaland   
2                caliban             beyonce  ...                rihanna   
3      breaking benjamin             editors  ...      justin timberlake   
4        subway to sally          the smiths  ...          nelly furtado   
5       three days grace  christina aguilera  ...                   mika   
6           cypress hill       lenny kravitz  ...                  jay-z   
7            korpiklaani     michael jackson  ...         james morrison   
8                  opeth          hoobastank  ...           fall out boy   
9         britney spears        babyshambles  ...  red hot chili peppers   
10  bring me the horizon      the libertines  ...               deftones   
11            arch enemy      sufjan stevens  ...            korpiklaani   

            tom waits              tool          tori amos             travis  \
1           tom waits      yann tiersen          tori amos   a perfect circle   
2        babyshambles              tool              bjork               abba   
3        jimi hendrix  boards of canada  alanis morissette              ac/dc   
4         arcade fire       equilibrium        damien rice         adam green   
5           bob dylan        digitalism            placebo          aerosmith   
6        bad religion    porcupine tree                air                afi   
7             editors      dimmu borgir          faithless                air   
8   bruce springsteen             dredg           the cure  alanis morissette   
9           the clash           volbeat             r.e.m.       alexisonfire   
10    franz ferdinand         radiohead          radiohead        alicia keys   
11         the smiths     the offspring               muse   all that remains   

                    trivium               u2          underoath  \
1                   trivium               u2          underoath   
2             parkway drive  robbie williams  killswitch engage   
3       

In [581]:
# Dropping the first row as it is redundant with the column names
item_similarity_df = item_similarity_df.drop(item_similarity_df.index[0])

In [582]:
item_similarity_df.head(10)

a perfect circle             abba            ac/dc           adam green  \
2                abba      hans zimmer       hammerfall       nouvelle vague   
3               ac/dc    frank sinatra       in extremo     three days grace   
4          adam green     howard shore        metallica             the fray   
5           aerosmith    elvis presley    dream theater                keane   
6                 afi  groove coverage   blind guardian       tegan and sara   
7                 air        faithless  bloodhound gang  belle and sebastian   
8   alanis morissette       papa roach        nightwish          the strokes   
9        alexisonfire      limp bizkit   marilyn manson           razorlight   
10        alicia keys          scooter    frank sinatra         farin urlaub   
11   all that remains        nightwish     apocalyptica            the kooks   

         aerosmith                afi                air alanis morissette  \
2           staind           paramore               moby         the clash   
3       maria mena             sum 41          faithless            r.e.m.   
4   flogging molly  breaking benjamin          radiohead             bjork   
5     bad religion               nofx  alanis morissette         tori amos   
6        morcheeba          anti-flag              bjork      jimi hendrix   
7     eric clapton          blink-182          nada surf           nirvana   
8       papa roach     good charlotte          tori amos       damien rice   
9       audioslave          peter fox        the streets      bad religion   
10       manu chao             clueso                atb         motorhead   
11      in extremo            ramones          daft punk          the cure   

            alexisonfire         alicia keys  ...              timbaland  \
2                caliban             beyonce  ...                rihanna   
3      breaking benjamin             editors  ...      justin timberlake   
4        subway to sally          the smiths  ...          nelly furtado   
5       three days grace  christina aguilera  ...                   mika   
6           cypress hill       lenny kravitz  ...                  jay-z   
7            korpiklaani     michael jackson  ...         james morrison   
8                  opeth          hoobastank  ...           fall out boy   
9         britney spears        babyshambles  ...  red hot chili peppers   
10  bring me the horizon      the libertines  ...               deftones   
11            arch enemy      sufjan stevens  ...            korpiklaani   

            tom waits              tool          tori amos             travis  \
2        babyshambles              tool              bjork               abba   
3        jimi hendrix  boards of canada  alanis morissette              ac/dc   
4         arcade fire       equilibrium        damien rice         adam green   
5           bob dylan        digitalism            placebo          aerosmith   
6        bad religion    porcupine tree                air                afi   
7             editors      dimmu borgir          faithless                air   
8   bruce springsteen             dredg           the cure  alanis morissette   
9           the clash           volbeat             r.e.m.       alexisonfire   
10    franz ferdinand         radiohead          radiohead        alicia keys   
11         the smiths     the offspring               muse   all that remains   

                    trivium               u2          underoath  \
2             parkway drive  robbie williams  killswitch engage   
3          all that remains          misfits             atreyu   
4              machine head        green day       lostprophets   
5                  chimaira     depeche mode         stone sour   
6                    slayer        peter fox       cypress hill   
7                  soilwork   kelly clarkson          cat power   
8            as i lay dying     dire straits           deftones   


### A. Recommend 10 songs to users who have listened to 'u2' and 'pink floyd'

In [583]:
top_10_similar_artists = pd.DataFrame(item_similarity_df.loc[:,['pink floyd','u2']])
top_10_similar_artists

pink floyd               u2
2                genesis  robbie williams
3                  queen          misfits
4           led zeppelin        green day
5        sonic syndicate     depeche mode
6            hans zimmer        peter fox
7   funeral for a friend   kelly clarkson
8            david bowie     dire straits
9               coldplay    enter shikari
10          howard shore          madonna
11    the rolling stones      johnny cash

# User Based collaborative Filtering

In [592]:
# Building a co-occurrence matrix to find how many times items/artists have appeared in the radio songs matrix together
df = pd.read_csv('radio_songs.csv')
user_based_df = df
user_based_df.set_index('user', inplace = True)
original_df = np.array(user_based_df)
transpose_df = np.array(user_based_df.T)


In [593]:
# Co-occurence matrix is the cross product between the original matrix and its transpose
co_occurence_matrix = np.dot(transpose_df,original_df)
np.fill_diagonal(co_occurence_matrix, 0)
co_occur_df = pd.DataFrame(co_occurence_matrix, columns = user_based_df.columns, index = user_based_df.columns)
co_occur_df

a perfect circle  abba  ac/dc  adam green  aerosmith  afi  \
a perfect circle                 0     0      0           0          0    0   
abba                             0     0      0           0          0    0   
ac/dc                            0     0      0           0          0    1   
adam green                       0     0      0           0          0    0   
aerosmith                        0     0      0           0          0    0   
...                            ...   ...    ...         ...        ...  ...   
trivium                          0     0      0           0          0    0   
u2                               0     0      1           0          0    0   
underoath                        0     0      0           0          0    0   
volbeat                          0     0      1           0          0    0   
yann tiersen                     0     0      0           0          0    0   

                  air  alanis morissette  alexisonfire  alicia keys  ...  \
a perfect circle    0                  0             0            0  ...   
abba                0                  0             0            0  ...   
ac/dc               0                  0             0            0  ...   
adam green          0                  0             0            0  ...   
aerosmith           0                  0             0            0  ...   
...               ...                ...           ...          ...  ...   
trivium             0                  0             0            0  ...   
u2                  0                  0             0            0  ...   
underoath           0                  0             1            0  ...   
volbeat             0                  0             0            0  ...   
yann tiersen        0                  0             0            0  ...   

                  timbaland  tom waits  tool  tori amos  travis  trivium  u2  \
a perfect circle          0          0     0          0       0        0   0   
abba                      0          0     0          0       0        0   0   
ac/dc                     0          0     0          0       0        0   1   
adam green                0          0     0          0       0        0   0   
aerosmith                 0          0     0          0       0        0   0   
...                     ...        ...   ...        ...     ...      ...  ..   
trivium                   0          0     0          0       0        0   0   
u2                        0          0     0          0       0        0   0   
underoath                 0          1     0          0       0        0   0   
volbeat                   0          0     1          0       0        1   1   
yann tiersen              0          0     1          0       0        0   0   

                  underoath  volbeat  yann tiersen  
a perfect circle          0        0             0  
abba                      0        0             0  
ac/dc                     0        1             0  
adam green                0        0             0  
aerosmith                 0        0             0  
...                     ...      ...           ...  
trivium                   0        1             0  
u2                        0        1             0  
underoath                 0        0             0  
volbeat                   0        0             1  
yann tiersen              0        1             0  

[285 rows x 285 columns]

In [594]:
# Building a user-item recommendation matrix first
user_item_matrix = np.dot(original_df, co_occurence_matrix)
non_zero_loc = pd.np.nonzero(original_df)
user_item_matrix[non_zero_loc] = 0
user_recommend_df = pd.DataFrame(user_item_matrix, columns = user_based_df.columns, index = user_based_df.index)
user_recommend_df

a perfect circle  abba  ac/dc  adam green  aerosmith  afi  air  \
user                                                                   
1                    0     0      4           1          1    4    3   
33                   0     2     12           0          2   14   10   
42                   0     2      7           1          1    3    0   
51                   0     0      8           5          2    8    6   
62                   0     0     12           4          3   10    8   
...                ...   ...    ...         ...        ...  ...  ...   
1566                 0     0      1           0          0    0    0   
1586                 0     2     10           1          3    8    5   
1589                 0     2      7           0          0    4    1   
1601                 0     0      1           1          0    0    2   
1606                 0     0      1           0          1    0    1   

      alanis morissette  alexisonfire  alicia keys  ...  timbaland  tom waits  \
user                                                ...                         
1                     3             2            3  ...          7          7   
33                    2             9            7  ...         11          8   
42                    0             3            0  ...          0          0   
51                    1             4            5  ...          5         10   
62                    2             6            6  ...         11          8   
...                 ...           ...          ...  ...        ...        ...   
1566                  0             0            2  ...          1          1   
1586                  2             4            0  ...         12          4   
1589                  1             3            0  ...          2          0   
1601                  0             0            3  ...          0          5   
1606                  1             0            1  ...          0          4   

      tool  tori amos  travis  trivium  u2  underoath  volbeat  yann tiersen  
user                                                                          
1        0          1       0        0   3          2        6             0  
33       0          2       0        1  10         11        9             0  
42       0          0       0        3   0          2        1             0  
51       0          1       0        0   5          5        5             0  
62       0          1       0        1   7          6        8             0  
...    ...        ...     ...      ...  ..        ...      ...           ...  
1566     0          0       0        0   0          0        0             0  
1586     1          1       0        0   9          4        4             1  
1589     2          1       0        3   0          1        3             2  
1601     0          0       0        0   2          1        1             0  
1606     0          0       0        0   0          0        1             0  

[100 rows x 285 columns]

In [596]:
# Replacing null values in the user recommendation sparse matrix by songs/artists/item Average
artists_final = user_recommend_df.fillna(user_recommend_df.mean(axis=0))  # row-wise average

# Replacing the null values in the user recommendation sparse matrix by user rating Average
user_final = user_recommend_df.apply(lambda row: row.fillna(row.mean()), axis=1)  # column-wise average

In [597]:
artists_final

a perfect circle  abba  ac/dc  adam green  aerosmith  afi  air  \
user                                                                   
1                    0     0      4           1          1    4    3   
33                   0     2     12           0          2   14   10   
42                   0     2      7           1          1    3    0   
51                   0     0      8           5          2    8    6   
62                   0     0     12           4          3   10    8   
...                ...   ...    ...         ...        ...  ...  ...   
1566                 0     0      1           0          0    0    0   
1586                 0     2     10           1          3    8    5   
1589                 0     2      7           0          0    4    1   
1601                 0     0      1           1          0    0    2   
1606                 0     0      1           0          1    0    1   

      alanis morissette  alexisonfire  alicia keys  ...  timbaland  tom waits  \
user                                                ...                         
1                     3             2            3  ...          7          7   
33                    2             9            7  ...         11          8   
42                    0             3            0  ...          0          0   
51                    1             4            5  ...          5         10   
62                    2             6            6  ...         11          8   
...                 ...           ...          ...  ...        ...        ...   
1566                  0             0            2  ...          1          1   
1586                  2             4            0  ...         12          4   
1589                  1             3            0  ...          2          0   
1601                  0             0            3  ...          0          5   
1606                  1             0            1  ...          0          4   

      tool  tori amos  travis  trivium  u2  underoath  volbeat  yann tiersen  
user                                                                          
1        0          1       0        0   3          2        6             0  
33       0          2       0        1  10         11        9             0  
42       0          0       0        3   0          2        1             0  
51       0          1       0        0   5          5        5             0  
62       0          1       0        1   7          6        8             0  
...    ...        ...     ...      ...  ..        ...      ...           ...  
1566     0          0       0        0   0          0        0             0  
1586     1          1       0        0   9          4        4             1  
1589     2          1       0        3   0          1        3             2  
1601     0          0       0        0   2          1        1             0  
1606     0          0       0        0   0          0        1             0  

[100 rows x 285 columns]

In [598]:
user_final

a perfect circle  abba  ac/dc  adam green  aerosmith  afi  air  \
user                                                                   
1                    0     0      4           1          1    4    3   
33                   0     2     12           0          2   14   10   
42                   0     2      7           1          1    3    0   
51                   0     0      8           5          2    8    6   
62                   0     0     12           4          3   10    8   
...                ...   ...    ...         ...        ...  ...  ...   
1566                 0     0      1           0          0    0    0   
1586                 0     2     10           1          3    8    5   
1589                 0     2      7           0          0    4    1   
1601                 0     0      1           1          0    0    2   
1606                 0     0      1           0          1    0    1   

      alanis morissette  alexisonfire  alicia keys  ...  timbaland  tom waits  \
user                                                ...                         
1                     3             2            3  ...          7          7   
33                    2             9            7  ...         11          8   
42                    0             3            0  ...          0          0   
51                    1             4            5  ...          5         10   
62                    2             6            6  ...         11          8   
...                 ...           ...          ...  ...        ...        ...   
1566                  0             0            2  ...          1          1   
1586                  2             4            0  ...         12          4   
1589                  1             3            0  ...          2          0   
1601                  0             0            3  ...          0          5   
1606                  1             0            1  ...          0          4   

      tool  tori amos  travis  trivium  u2  underoath  volbeat  yann tiersen  
user                                                                          
1        0          1       0        0   3          2        6             0  
33       0          2       0        1  10         11        9             0  
42       0          0       0        3   0          2        1             0  
51       0          1       0        0   5          5        5             0  
62       0          1       0        1   7          6        8             0  
...    ...        ...     ...      ...  ..        ...      ...           ...  
1566     0          0       0        0   0          0        0             0  
1586     1          1       0        0   9          4        4             1  
1589     2          1       0        3   0          1        3             2  
1601     0          0       0        0   2          1        1             0  
1606     0          0       0        0   0          0        1             0  

[100 rows x 285 columns]

In [599]:
# we still see a lot of null values in the sparse matrix
# Building a user similarity matrix using cosine similarity on the user_final sparse matrix
cosine_sim = cosine_similarity(user_final)
np.fill_diagonal(cosine_sim, 0 )
user_cosine_similarity = pd.DataFrame(cosine_sim,index=user_final.index)
user_cosine_similarity.columns=user_final.index
user_cosine_similarity

user      1         33        42        51        62        75        130   \
user                                                                         
1     0.000000  0.774491  0.722210  0.778786  0.828322  0.813318  0.261443   
33    0.774491  0.000000  0.644159  0.733461  0.725955  0.786510  0.259527   
42    0.722210  0.644159  0.000000  0.599324  0.644072  0.733917  0.223374   
51    0.778786  0.733461  0.599324  0.000000  0.783523  0.781119  0.222765   
62    0.828322  0.725955  0.644072  0.783523  0.000000  0.793753  0.242916   
...        ...       ...       ...       ...       ...       ...       ...   
1566  0.491905  0.444140  0.325567  0.500302  0.468054  0.401867  0.212000   
1586  0.807409  0.741296  0.725053  0.737292  0.771773  0.772369  0.307630   
1589  0.739642  0.671360  0.812858  0.646218  0.685568  0.745555  0.233727   
1601  0.624969  0.502674  0.307031  0.616271  0.584117  0.501482  0.268926   
1606  0.690931  0.614515  0.491474  0.623263  0.618053  0.573729  0.173702   

user      141       144       150   ...      1521      1530      1536  \
user                                ...                                 
1     0.652686  0.582103  0.829380  ...  0.785397  0.131954  0.803445   
33    0.614744  0.535877  0.786478  ...  0.738860  0.146559  0.759817   
42    0.740794  0.266828  0.707162  ...  0.815468  0.017082  0.672418   
51    0.561243  0.604631  0.794632  ...  0.699702  0.119779  0.761227   
62    0.591139  0.533669  0.814137  ...  0.724346  0.106841  0.749313   
...        ...       ...       ...  ...       ...       ...       ...   
1566  0.329006  0.497490  0.442272  ...  0.416954  0.170226  0.475082   
1586  0.651038  0.456413  0.814972  ...  0.773202  0.051882  0.736492   
1589  0.718546  0.353536  0.811084  ...  0.796419  0.035747  0.687563   
1601  0.313455  0.783990  0.581488  ...  0.440447  0.365606  0.583553   
1606  0.476711  0.715613  0.637331  ...  0.608482  0.227714  0.580162   

user      1545      1549      1566      1586      1589      1601      1606  
user                                                                        
1     0.849052  0.643286  0.491905  0.807409  0.739642  0.624969  0.690931  
33    0.760235  0.555025  0.444140  0.741296  0.671360  0.502674  0.614515  
42    0.752830  0.673191  0.325567  0.725053  0.812858  0.307031  0.491474  
51    0.718480  0.569667  0.500302  0.737292  0.646218  0.616271  0.623263  
62    0.764261  0.577305  0.468054  0.771773  0.685568  0.584117  0.618053  
...        ...       ...       ...       ...       ...       ...       ...  
1566  0.410909  0.265466  0.000000  0.470271  0.313817  0.625024  0.594457  
1586  0.752335  0.620950  0.470271  0.000000  0.727435  0.514896  0.588250  
1589  0.739328  0.748935  0.313817  0.727435  0.000000  0.377908  0.552917  
1601  0.520082  0.306392  0.625024  0.514896  0.377908  0.000000  0.699955  
1606  0.586525  0.453204  0.594457  0.588250  0.552917  0.699955  0.000000  

[100 rows x 100 columns]

In [600]:
# Building a user similarity matrix using cosine similarity on the artists_final sparse matrix
cos = cosine_similarity(artists_final)
np.fill_diagonal(cos, 0 )
artists_cosine_similarity = pd.DataFrame(cos,index=artists_final.index)
artists_cosine_similarity.columns=user_final.index
artists_cosine_similarity

user      1         33        42        51        62        75        130   \
user                                                                         
1     0.000000  0.774491  0.722210  0.778786  0.828322  0.813318  0.261443   
33    0.774491  0.000000  0.644159  0.733461  0.725955  0.786510  0.259527   
42    0.722210  0.644159  0.000000  0.599324  0.644072  0.733917  0.223374   
51    0.778786  0.733461  0.599324  0.000000  0.783523  0.781119  0.222765   
62    0.828322  0.725955  0.644072  0.783523  0.000000  0.793753  0.242916   
...        ...       ...       ...       ...       ...       ...       ...   
1566  0.491905  0.444140  0.325567  0.500302  0.468054  0.401867  0.212000   
1586  0.807409  0.741296  0.725053  0.737292  0.771773  0.772369  0.307630   
1589  0.739642  0.671360  0.812858  0.646218  0.685568  0.745555  0.233727   
1601  0.624969  0.502674  0.307031  0.616271  0.584117  0.501482  0.268926   
1606  0.690931  0.614515  0.491474  0.623263  0.618053  0.573729  0.173702   

user      141       144       150   ...      1521      1530      1536  \
user                                ...                                 
1     0.652686  0.582103  0.829380  ...  0.785397  0.131954  0.803445   
33    0.614744  0.535877  0.786478  ...  0.738860  0.146559  0.759817   
42    0.740794  0.266828  0.707162  ...  0.815468  0.017082  0.672418   
51    0.561243  0.604631  0.794632  ...  0.699702  0.119779  0.761227   
62    0.591139  0.533669  0.814137  ...  0.724346  0.106841  0.749313   
...        ...       ...       ...  ...       ...       ...       ...   
1566  0.329006  0.497490  0.442272  ...  0.416954  0.170226  0.475082   
1586  0.651038  0.456413  0.814972  ...  0.773202  0.051882  0.736492   
1589  0.718546  0.353536  0.811084  ...  0.796419  0.035747  0.687563   
1601  0.313455  0.783990  0.581488  ...  0.440447  0.365606  0.583553   
1606  0.476711  0.715613  0.637331  ...  0.608482  0.227714  0.580162   

user      1545      1549      1566      1586      1589      1601      1606  
user                                                                        
1     0.849052  0.643286  0.491905  0.807409  0.739642  0.624969  0.690931  
33    0.760235  0.555025  0.444140  0.741296  0.671360  0.502674  0.614515  
42    0.752830  0.673191  0.325567  0.725053  0.812858  0.307031  0.491474  
51    0.718480  0.569667  0.500302  0.737292  0.646218  0.616271  0.623263  
62    0.764261  0.577305  0.468054  0.771773  0.685568  0.584117  0.618053  
...        ...       ...       ...       ...       ...       ...       ...  
1566  0.410909  0.265466  0.000000  0.470271  0.313817  0.625024  0.594457  
1586  0.752335  0.620950  0.470271  0.000000  0.727435  0.514896  0.588250  
1589  0.739328  0.748935  0.313817  0.727435  0.000000  0.377908  0.552917  
1601  0.520082  0.306392  0.625024  0.514896  0.377908  0.000000  0.699955  
1606  0.586525  0.453204  0.594457  0.588250  0.552917  0.699955  0.000000  

[100 rows x 100 columns]

# B. Find user most similar to user 1606 (at row index 99). Use user-user collaborative filtering with cosine similarity

In [601]:
def find_n_user_neighbours(matrix,n):
    sorting = np.argsort(df.values, axis=1)[:, :n]
    matrix = matrix.apply(lambda k: pd.Series(k.sort_values(ascending=False)
           .iloc[:n].index,index=['top_{}'.format(i) for i in range(1, n+1)]), axis=1)
    return matrix

In [602]:
# Finding the top 10 most similar users for each user
top_10_similar_users = find_n_user_neighbours(user_cosine_similarity,10)
top_10_similar_users

top_1  top_2  top_3  top_4  top_5  top_6  top_7  top_8  top_9  top_10
user                                                                       
1       715   1479    648   1545    626    205    150    956     62    1207
33     1361     75    150    951   1233    948      1    794   1487     447
42     1509    975   1037   1521   1589    367    299    447    956    1545
51      948    852    642    150   1487    626   1291    383    313    1361
62     1361      1    948    150   1207    852   1487   1201    626      75
...     ...    ...    ...    ...    ...    ...    ...    ...    ...     ...
1566   1601    715   1606   1144   1334    953    438   1083    508     948
1586    150   1336    642   1207   1381      1    383    736   1233     956
1589   1037   1381   1179   1509     42    150   1083    472   1521     890
1601    144    830    438    953   1144   1264    906    715    508     371
1606   1334   1144    144    715    953   1601    508   1083    948       1

[100 rows x 10 columns]

In [607]:
# Since the user 1606 is the absolute bottom of the matrix , we retrieve its top 10 neighbours using the tail command
most_similar_user = top_10_similar_users.tail(1).transpose().head(1)
most_similar_user

user   1606
top_1  1334

Its quite obvious that the user with user_id = 1334 is the most similar user to user 1606

Now lets find the songs listened to by the most similar user(1334) in order to recommended songs for user 1606

# List the recommended songs for user 1606 (Hint: find the songs listened to by the most similar user)

In [612]:
df = pd.read_csv('radio_songs.csv')

In [617]:
most_similar_user_id = 1334
most_similar_user_index = df[df['user'] == most_similar_user_id].index.tolist()[0]
most_similar_user_index

79

In [631]:
# Songs that the user with id = 1334 and row index = 79 has already listened to
most_similar_user_songs = df.iloc[most_similar_user_index]
most_similar_user_songs = most_similar_user_songs[most_similar_user_songs >0].index.values
most_similar_user_songs = pd.DataFrame(most_similar_user_songs)
most_similar_user_songs

0
0                       user
1                       blur
2   bob marley & the wailers
3                  cat power
4                  daft punk
5                david bowie
6                      feist
7               joy division
8                  manu chao
9            michael jackson
10               the beatles
11                  the cure

In [632]:
# Dropping the first row as it is redundant with the column name
most_similar_user_songs = most_similar_user_songs.drop(most_similar_user_songs.index[0])


In [634]:
most_similar_user_songs.columns = ['songs']
most_similar_user_songs

songs
1                       blur
2   bob marley & the wailers
3                  cat power
4                  daft punk
5                david bowie
6                      feist
7               joy division
8                  manu chao
9            michael jackson
10               the beatles
11                  the cure

# C. How many of the recommended songs has already been listened to by user 1606?

In [625]:
user_id = 1606
user_index = df[df['user'] == user_id].index.tolist()[0]
user_index

99

In [627]:
# Songs that the user with id = 1606 and row index = 99 has already listened to
user_songs = df.iloc[user_index]
user_songs = user_songs[user_songs >0].index.values
user_songs = pd.DataFrame(user_songs)
user_songs = user_songs.drop(user_songs.index[0])
user_songs

0
1           abba
2  elvis presley
3  frank sinatra
4    the beatles

In [635]:
user_songs.columns = ['songs']
user_songs

songs
1           abba
2  elvis presley
3  frank sinatra
4    the beatles

In [637]:
already_listened_songs = pd.merge(most_similar_user_songs, user_songs, how='inner', on=['songs'])
already_listened_songs

songs
0  the beatles

Looks like the "The beatles" is the only song that is alreday listened by the user 1606 that was recommended by the user 1334.

So we cannot recommend "The Beatles" songs to the user 1606 because he/she has already listened to it.

In [639]:
final_recommended_songs = pd.concat([most_similar_user_songs, already_listened_songs])
final_recommended_songs = final_recommended_songs.drop_duplicates(keep=False)
final_recommended_songs

songs
1                       blur
2   bob marley & the wailers
3                  cat power
4                  daft punk
5                david bowie
6                      feist
7               joy division
8                  manu chao
9            michael jackson
11                  the cure

# 2. Conceptual questions:

1. Name 2 other similarity measures that you can use instead of cosine similarity above.

Cosine similarity is one of the most common similarity measure used for the collaborative filtering . Besides cosine similarity , we can also use pearson correlation or Euclidean distance measure as well.

Cosine similarity measure can be applied when we have a sparse matrix(ratings are undefined or null) like the one we just worked on(radio_songs.csv). Cosine similarity normalizes the scales of the features by default because it doesnt care about the magnitude. Its better not to use cosine similarity on ordinal categorical data that is not centered or even binary/unary data which happens in the implicit feedback use cases.

Euclidean distance : We all know that the similar items lie in close proximity or vicinity to each other if we plot them in multi-dimensional space. Euclidean distance helps in calculating the distance between the items based on that distance and then recommend items or products to the users.
Euclidean proximity/distance similarity measure can be used if the input data is not sparse and the values within the data matrix or the values of the features/atrributes are significant. Euclidean measure helps to balance the sensitivity with respect to the vector direction withoit being overtly biased to popular items. Optimizing the recommender systems models using euclidean measure gives more intuitive results.

Pearson correlation : This measure indicates how much two products or items are correlated .Their similarity increases with their similarity
Pearson correlation measure can be selected when ratings or the values of different attrbutes/features are on different scale and also when the input data is subject to user-bias. Pearson correlation also normalizes the scales of the user ratings by default like cosine. Pearson correaltion helps to mitigate the bias towards popular itemsbut also has a drawback of recommending items that are not popular.

We can also select adjusted cosine particularly to adjust for the user-bias specifically for the item-based approach.
Adjusted cosine works by substracting individual user's average rating from each co-rated pair.

2. What is needed to build a Content-Based Recommender system?

Content or the attributes of an item or product is needed to build a content based recommendation system. It works by considering or tagging the products or items using certain keywords in order to understand what the user likes , then query or look up in the database with those keywords and then recommend other different products or items with similar attributes or tags. Content based recommender system helps in predicting the rating or preference that any particular user would give to an item or product.

Content based recommender systems initially need the data that the users provides whether it is explicit like a ratig or implicit like clicking on a link. On the basis of this obtained data, profiles of the users is created, which in turn helps in making suggestions to the user. This recommender system becomes more and more accurate in terms of predictions/recommendations as the users provide more inputs or takes actions on the suggestions/recommendations.

There are 3 basic structures in a content based recommender systems : User profile , item profile and a utility matrix

User profile :  Within user profile , vectors are created based on user's preference 

item profile : Item profile holds the important attributes/tags or charecteristics of the items .

utility matrix : Utility matrix describes the reltionship between the user and the item which is then fed into the content based recommendation system. Utility matrix represents the data obtained from the user and then find the relations between the songs/items/products in terms of which were disliked and liked. A degree of preference is assigned to each user-item pair. This helps in forming a user matrix with respective items in order to identify their preference relationship.

3. Name 2 methods to evaluate your recommender system.


Since we worked on a binary unary matrix , it would make sense if our collaborative filtering recommendation system models are evaluated on precision , recall , f1 score etc.

Precision : Precision would indicate out of all the songs or albums that were recommended , how many of those did user actually like/purchase/listened to ? Precision is given by true positive/(true positive + false positive)
The denominator represents the total number of songs that were recommended to a particular user and the numerator indicates out of all of those recommendations(in the denominator) made , how many did the user actually ended up liking/purchasing/listening .If we have a larger precision , then it means that the recommendations were better or accurate.
Precision will be 0.8 if 5 songs were recommended by the model and out of which the user liked/purchased/listened to 4 of those.


Recall : Recall is a measure of what proportion of songs that a user liked/listened/purchased were actually recommended. Recall is given by : True positive/( true positive + false negative). The true positive part or the numerator indicates the number of songs recommended to a user that she/he likes and then the denominatir represents total number of songs that he/she listened to/purchased/liked. If the recall is bigger , it means our recommendation engine is performing better. 
The recal will have a value of 0.6 if the user likes/puchases/listend to 5 items and out of those 5 , 3 were recommended by the model.


MAP at k (Mean Average Precision at cutoff k): Since recall and precision do not care about the ordering of our song recommendations , precision at cutoff k is the value of the precision that is calculated by taking into consideration only the subset of the recommendations from rank 1 to k.

RMSE and MAE can be applied to non-binary matrices which may not be applicable to our use case but worth mentioning because they are widely used.

RMSE(root mean squared error is the most widely used evaluation metric for the recommender systems. RMSE puts higher penalty or rather punishes more larger errors.

MAE( Mean absolute error) is also another popular metric for meansuring how close is our prediction (of the recommender system) numerically from the real value. MAE punishes or puts penalty on every error regardless of whether its small or big.



# 3. Challenge question - extra points (20)

## 1. For each song for the user row, get the top 10 similar songs and their similarity score.

In [651]:
# Building a temporary place holder matrix for the user_item similarities
user_item_df = pd.DataFrame(index=df.index,columns=df.columns)

In [652]:
user_item_df.iloc[:,:1] = df.iloc[:,:1]

In [653]:
user_item_df

user a perfect circle abba ac/dc adam green aerosmith  afi  air  \
0      1              NaN  NaN   NaN        NaN       NaN  NaN  NaN   
1     33              NaN  NaN   NaN        NaN       NaN  NaN  NaN   
2     42              NaN  NaN   NaN        NaN       NaN  NaN  NaN   
3     51              NaN  NaN   NaN        NaN       NaN  NaN  NaN   
4     62              NaN  NaN   NaN        NaN       NaN  NaN  NaN   
..   ...              ...  ...   ...        ...       ...  ...  ...   
95  1566              NaN  NaN   NaN        NaN       NaN  NaN  NaN   
96  1586              NaN  NaN   NaN        NaN       NaN  NaN  NaN   
97  1589              NaN  NaN   NaN        NaN       NaN  NaN  NaN   
98  1601              NaN  NaN   NaN        NaN       NaN  NaN  NaN   
99  1606              NaN  NaN   NaN        NaN       NaN  NaN  NaN   

   alanis morissette alexisonfire  ... timbaland tom waits tool tori amos  \
0                NaN          NaN  ...       NaN       NaN  NaN       NaN   
1                NaN          NaN  ...       NaN       NaN  NaN       NaN   
2                NaN          NaN  ...       NaN       NaN  NaN       NaN   
3                NaN          NaN  ...       NaN       NaN  NaN       NaN   
4                NaN          NaN  ...       NaN       NaN  NaN       NaN   
..               ...          ...  ...       ...       ...  ...       ...   
95               NaN          NaN  ...       NaN       NaN  NaN       NaN   
96               NaN          NaN  ...       NaN       NaN  NaN       NaN   
97               NaN          NaN  ...       NaN       NaN  NaN       NaN   
98               NaN          NaN  ...       NaN       NaN  NaN       NaN   
99               NaN          NaN  ...       NaN       NaN  NaN       NaN   

   travis trivium   u2 underoath volbeat yann tiersen  
0     NaN     NaN  NaN       NaN     NaN          NaN  
1     NaN     NaN  NaN       NaN     NaN          NaN  
2     NaN     NaN  NaN       NaN     NaN          NaN  
3     NaN     NaN  NaN       NaN     NaN          NaN  
4     NaN     NaN  NaN       NaN     NaN          NaN  
..    ...     ...  ...       ...     ...          ...  
95    NaN     NaN  NaN       NaN     NaN          NaN  
96    NaN     NaN  NaN       NaN     NaN          NaN  
97    NaN     NaN  NaN       NaN     NaN          NaN  
98    NaN     NaN  NaN       NaN     NaN          NaN  
99    NaN     NaN  NaN       NaN     NaN          NaN  

[100 rows x 286 columns]

In [654]:
# Getting similarity score
def get_similarity_score(purchase_history, similarity_scores):
   return sum(purchase_history*similarity_scores)/sum(similarity_scores)

In [692]:
# Creating a placeholder matrix for item-item similarity
placeholder_df = pd.DataFrame(index=artists_matrix.columns,columns=artists_matrix.columns)

In [693]:
for i in range(0,len(placeholder_df.columns)) :
    # Looping through each of the artists/songs columns
    for j in range(0,len(placeholder_df.columns)) :
# Filling in the NaNs in the temp_df or the placeholder matrix with the item-item similarities using the spatial distance with cosine
      placeholder_df.iloc[i,j] = 1 - cosine(artists_matrix.iloc[:,i],artists_matrix.iloc[:,j])

In [701]:
# Building a close neighbourhood for closest similar items/artists
songs_neighbourhood = pd.DataFrame(index=placeholder_df.columns,columns=range(1,11))

In [702]:
# Looping through the entire songs_neighbourhood matrix/item-similarity matrix and filling in the values with the closest neighbourhood songs/items/artists
for i in range(0,len(placeholder_df.columns)):
    songs_neighbourhood.iloc[i,:10] = placeholder_df.iloc[0:,i].sort_values(ascending=False)[:10].index

In [703]:
songs_neighbourhood

1                  2                 3  \
a perfect circle  a perfect circle               abba             ac/dc   
abba                          abba        hans zimmer     frank sinatra   
ac/dc                        ac/dc         hammerfall        in extremo   
adam green              adam green     nouvelle vague  three days grace   
aerosmith                aerosmith             staind        maria mena   
...                            ...                ...               ...   
trivium                    trivium      parkway drive  all that remains   
u2                              u2    robbie williams           misfits   
underoath                underoath  killswitch engage            atreyu   
volbeat                    volbeat       yann tiersen              tool   
yann tiersen          yann tiersen               tool  boards of canada   

                                 4                  5                      6  \
a perfect circle        adam green          aerosmith                    afi   
abba                  howard shore      elvis presley        groove coverage   
ac/dc                    metallica      dream theater         blind guardian   
adam green                the fray              keane         tegan and sara   
aerosmith           flogging molly       bad religion              morcheeba   
...                            ...                ...                    ...   
trivium               machine head           chimaira                 slayer   
u2                       green day       depeche mode              peter fox   
underoath             lostprophets         stone sour           cypress hill   
volbeat           boards of canada  children of bodom  red hot chili peppers   
yann tiersen           equilibrium         digitalism         porcupine tree   

                                    7                  8                  9  \
a perfect circle                  air  alanis morissette       alexisonfire   
abba                        faithless         papa roach        limp bizkit   
ac/dc                 bloodhound gang          nightwish     marilyn manson   
adam green        belle and sebastian        the strokes         razorlight   
aerosmith                eric clapton         papa roach         audioslave   
...                               ...                ...                ...   
trivium                      soilwork     as i lay dying  children of bodom   
u2                     kelly clarkson       dire straits      enter shikari   
underoath                   cat power           deftones   three days grace   
volbeat                    digitalism       dimmu borgir       apocalyptica   
yann tiersen             dimmu borgir              dredg            volbeat   

                                 10  
a perfect circle        alicia keys  
abba                        scooter  
ac/dc                 frank sinatra  
adam green             farin urlaub  
aerosmith                 manu chao  
...                             ...  
trivium           heaven shall burn  
u2                          madonna  
underoath                rob zombie  
volbeat                dire straits  
yann tiersen              radiohead  

[285 rows x 10 columns]

In [709]:
# Dropping the first row as it is redundant with the column names
# songs_neighbourhood = songs_neighbourhood.drop(songs_neighbourhood.index[0])
# songs_neighbourhood

In [704]:
# Our approach is to find top 10 neighbours of the current song in iteration and then find top 10 closest neighbours using 
#item-item collaborative filtering  then getting the purchase record of the current user for each closest neighbour of the current song

# Looping through all the rows of the placeholder matrix for the user-item similarities and filling in values
for i in range(0,len(user_item_df.index)):
    # For each column or song/artist/item , we have to build a neighbourhood of closest similar songs( top 10)
    for j in range(1,len(user_item_df.columns)):
        user_iter = user_item_df.index[i]
        song_iter = user_item_df.columns[j]
 
        if df.loc[i][j] == 1:
            user_item_df.loc[i][j] = 0
        else:
            current_song_top_neighbours = songs_neighbourhood.loc[song_iter][1:10]
            top_closest_songs = placeholder_df.loc[song_iter].sort_values(ascending=False)[1:10]
            user_purchase_record = artists_matrix.loc[user_iter,current_song_top_neighbours]
 
            user_item_df.loc[i][j] = get_similarity_score(user_purchase_record,top_closest_songs)

In [710]:
# Get the top 5 recommended songs for each user
top_recommended_songs = pd.DataFrame(index=user_item_df.index, columns=['user','1','2','3','4','5'])
top_recommended_songs.iloc[0:,0] = user_item_df.iloc[:,0]

In [711]:
# Displaying the names of the recommended songs for each user
for i in range(0,len(user_df.index)):
    top_recommended_songs.iloc[i,1:] = user_item_df.iloc[i,:].sort_values(ascending=False).iloc[1:6,].index.transpose()

In [715]:
top_recommended_songs

user                1             2                   3                4  \
0      1      korpiklaani       nirvana           green day  subway to sally   
1     33          placebo     gentleman          bloc party         interpol   
2     42  subway to sally     rammstein      marilyn manson            ac/dc   
3     51      the subways       justice       kaiser chiefs        the kooks   
4     62          incubus   the strokes            paramore          nirvana   
..   ...              ...           ...                 ...              ...   
95  1566      alicia keys  joy division      james morrison             mika   
96  1586  black eyed peas       cascada  the pussycat dolls      iron maiden   
97  1589       hammerfall    in extremo               ac/dc    avril lavigne   
98  1601         coldplay         stars           pearl jam      arcade fire   
99  1606     eric clapton  howard shore       dream theater     apocalyptica   

                       5  
0   thievery corporation  
1   kings of convenience  
2         blind guardian  
3           foo fighters  
4                 sum 41  
..                   ...  
95          farin urlaub  
96     justin timberlake  
97       subway to sally  
98           james blunt  
99           hans zimmer  

[100 rows x 6 columns]

In [716]:
# Displaying the top 5 recommended songs for the user 1606(row index = 99)
top_5_user_1606 = top_recommended_songs.tail(1).transpose()
top_5_user_1606

99
user           1606
1      eric clapton
2      howard shore
3     dream theater
4      apocalyptica
5       hans zimmer